services:
  app:
    image: kdhyun422/my-app:${IMAGE_TAG}
    ports:
      - "80:8080"
    restart: unless-stopped

    env_file:
      - .env
      
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CONCURRENCY_ID: ${ CONCURRENCY_ID }
      CONCURRENCY_SECRET_KEY: ${ CONCURRENCY_SECRET_KEY }

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 3s
      retries: 5

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - "--global-response-templating"

