server:
  address: 0.0.0.0

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    com.example.logdemo: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
        exclude: env, heapdump, threaddump, configprops, quartz

jwt:
  secret-key: ${JWT_SECRET_KEY}

concurrency:
  endpoint: "https://ceos.diggindie.com"
  storeId: ${CONCURRENCY_ID}
  secret-key: ${CONCURRENCY_SECRET_KEY}